name: Solar System Workflow

on:
    workflow_dispatch:
    push:
        branches:
         - main
         - feature**
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: superuser
  MONGO_PASSWORD: SuperPassword ## can also be set from secrets ${{ secrets.MONGO_PASS }}

jobs:
    unit_test:
        stratergy:
          max-parallel: 2
          fail-fast: true
          matrix:
            os: [ubuntu-latest]
            node-version: [17,18,19]

            exclude:
              - os: ubuntu-latest
                node-version: 19

        runs-on: ${{ matrix.os }}

        steps:

            - name: Checkout the repo
              uses: actions/checkout@v5

            - name: Setup NodeJs version - 18   ### IN the virtual machine have NodeJs v18 installed
              uses:  actions/setup-node@v6
              with:
                node-version: ${{ matrix.node-version }}
            
            - name: Install required depedencies
              run: npm install
            
            - name: Run the test file
              run: npm test
            
            - name: Archive the test results
              uses: actions/upload-artifact@v4
              with:
                name: Test-Archives
                path: test-results.xml
